"use client";

import Link from "next/link";
import { useState } from "react";
import { motion } from "framer-motion";
import { SectionHead } from "./Mechanism";
import { Wordmark } from "@/components/Logo";
import { cn } from "@/lib/utils";

const QUESTIONS = [
  {
    q: "Why does signed code provenance need a blockchain at all?",
    a: "It needs an append-only log that no single party can rewrite, including the party being audited. A database owned by the tool vendor fails that test — if the vendor can edit history, the record proves nothing about the vendor. Solana is used here for cost and finality: a memo transaction settles in under a second and costs a fraction of a cent, which is the difference between sealing every patch and sealing the ones you remember to.",
  },
  {
    q: "What stops someone signing a patch they did not write?",
    a: "Nothing, and that is the correct answer. A signature attests that the holder of a key vouched for a patch, not that they typed it. The value is in the chain of accountability: if a change breaks production, the seal names the key that approved it and the model that generated it. Attribution, not surveillance.",
  },
  {
    q: "Does my private key ever leave the browser?",
    a: "No. The session key is generated by the Web Crypto path in your tab and written to localStorage. Only the public key and the detached signature are sent. The server refuses to spend a lamport until that signature verifies, so a forged request is rejected before it costs anything.",
  },
  {
    q: "Is this a fork of VS Code?",
    a: "No. The editor surface is Monaco, which Microsoft publishes separately under MIT, and the terminal is xterm.js. Extension metadata comes from Open VSX, an Eclipse Foundation registry whose terms permit third-party clients. Nothing proprietary is copied and no licensing is circumvented.",
  },
  {
    q: "Which models can drive the agent?",
    a: "Anything exposing an OpenAI-compatible chat completions endpoint. The deployed build points at Groq for latency; changing two environment variables moves it to Anthropic, Gemini via a shim, or a model running on your own machine. No model is hardcoded into the client.",
  },
  {
    q: "Is this on mainnet?",
    a: "No. Devnet only, and every on-chain claim on this site says so. Mainnet requires a fee model and a funded relayer with real controls around it, neither of which exists yet.",
  },
];

export function Faq() {
  const [open, setOpen] = useState<number | null>(0);

  return (
    <section className="border-t border-line py-24">
      <div className="mx-auto max-w-[1200px] px-6">
        <SectionHead eyebrow="Questions" title="The ones worth asking" />
        <div className="mt-12 max-w-[820px]">
          {QUESTIONS.map((item, i) => {
            const isOpen = open === i;
            return (
              <div key={item.q} className="border-b border-line">
                <button
                  type="button"
                  onClick={() => setOpen(isOpen ? null : i)}
                  aria-expanded={isOpen}
                  className="flex w-full items-start gap-4 py-5 text-left"
                >
                  <span
                    className={cn(
                      "mt-1 grid size-5 shrink-0 place-items-center rounded-full border transition-colors duration-200",
                      isOpen
                        ? "border-brass text-brass"
                        : "border-line-strong text-faint",
                    )}
                    aria-hidden
                  >
                    <svg width="9" height="9" viewBox="0 0 9 9">
                      <path
                        d="M4.5 1v7M1 4.5h7"
                        stroke="currentColor"
                        strokeWidth="1.4"
                        strokeLinecap="round"
                        style={{
                          transition: "opacity 180ms",
                          opacity: isOpen ? 0 : 1,
                        }}
                      />
                      <path
                        d="M1 4.5h7"
                        stroke="currentColor"
                        strokeWidth="1.4"
                        strokeLinecap="round"
                      />
                    </svg>
                  </span>
                  <span
                    className={cn(
                      "flex-1 text-[16px] transition-colors duration-200",
                      isOpen ? "text-paper" : "text-muted",
                    )}
                  >
                    {item.q}
                  </span>
                </button>
                <motion.div
                  initial={false}
                  animate={{
                    height: isOpen ? "auto" : 0,
                    opacity: isOpen ? 1 : 0,
                  }}
                  transition={{ duration: 0.28, ease: [0.16, 1, 0.3, 1] }}
                  className="overflow-hidden"
                >
                  <p className="max-w-[68ch] pb-6 pl-9 text-[14.5px] leading-[1.7] text-muted">
                    {item.a}
                  </p>
                </motion.div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}

export function Cta() {
  return (
    <section className="relative overflow-hidden border-t border-line py-28">
      <div
        className="pointer-events-none absolute left-1/2 top-1/2 h-[300px] w-[700px] -translate-x-1/2 -translate-y-1/2 rounded-full opacity-[0.10] blur-[110px]"
        style={{ background: "radial-gradient(circle, #E6A94E 0%, transparent 70%)" }}
        aria-hidden
      />
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: "-80px" }}
        transition={{ duration: 0.55, ease: [0.16, 1, 0.3, 1] }}
        className="relative mx-auto max-w-[680px] px-6 text-center"
      >
        <h2 className="text-[clamp(1.9rem,4vw,2.75rem)] font-semibold leading-[1.1] tracking-[-0.03em] text-paper">
          Open a file. Ask for a change.
          <br />
          <span className="brass-text">Watch it get sealed.</span>
        </h2>
        <p className="mx-auto mt-5 max-w-[52ch] text-[15.5px] leading-[1.65] text-muted">
          The workbench needs no account and no wallet extension. It generates a
          signing key on first load and writes to devnet at your expense of nothing.
        </p>
        <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
          <Link
            href="/studio"
            className="rounded-[6px] bg-brass px-5 py-2.5 text-sm font-medium text-ink transition-[background-color,transform] duration-150 hover:bg-brass-hi active:scale-[0.985]"
          >
            Open the workbench
          </Link>
          <a
            href="https://github.com/bryankwandou/marque"
            target="_blank"
            rel="noreferrer noopener"
            className="rounded-[6px] border border-line-strong px-5 py-2.5 text-sm text-muted transition-colors duration-150 hover:border-brass hover:text-paper"
          >
            Read the source
          </a>
        </div>
      </motion.div>
    </section>
  );
}

export function Footer() {
  return (
    <footer className="border-t border-line py-12">
      <div className="mx-auto flex max-w-[1200px] flex-col gap-8 px-6 sm:flex-row sm:items-start sm:justify-between">
        <div className="max-w-[300px]">
          <Wordmark size={24} id="foot" />
          <p className="mt-3 text-[13px] leading-[1.6] text-faint">
            A browser code workspace that keeps a verifiable record of what its agents
            wrote. Devnet only.
          </p>
        </div>
        <div className="grid grid-cols-2 gap-x-12 gap-y-2 text-[13px] sm:grid-cols-3">
          <FooterCol
            title="Product"
            links={[
              { label: "Workbench", href: "/studio" },
              { label: "Mechanism", href: "/#mechanism" },
              { label: "Extensions", href: "/#registry" },
            ]}
          />
          <FooterCol
            title="Built on"
            links={[
              { label: "Open VSX", href: "https://open-vsx.org" },
              { label: "Monaco", href: "https://microsoft.github.io/monaco-editor/" },
              { label: "Solana", href: "https://solana.com" },
            ]}
          />
          <FooterCol
            title="Project"
            links={[
              { label: "Source", href: "https://github.com/bryankwandou/marque" },
              {
                label: "Explorer",
                href: "https://explorer.solana.com/?cluster=devnet",
              },
            ]}
          />
        </div>
      </div>
      <div className="mx-auto mt-10 max-w-[1200px] border-t border-line px-6 pt-6">
        <p className="font-mono text-[11.5px] text-faint">
          Marque is not affiliated with Microsoft, Google, or any editor vendor named
          on this site. Monaco and xterm.js are used under their own licences.
        </p>
      </div>
    </footer>
  );
}

function FooterCol({
  title,
  links,
}: {
  title: string;
  links: { label: string; href: string }[];
}) {
  return (
    <div>
      <h3 className="mb-2.5 font-mono text-[11px] uppercase tracking-[0.12em] text-faint">
        {title}
      </h3>
      <ul className="space-y-1.5">
        {links.map((l) => (
          <li key={l.label}>
            <a
              href={l.href}
              target={l.href.startsWith("http") ? "_blank" : undefined}
              rel={l.href.startsWith("http") ? "noreferrer noopener" : undefined}
              className="text-muted transition-colors duration-150 hover:text-paper"
            >
              {l.label}
            </a>
          </li>
        ))}
      </ul>
    </div>
  );
}
